builds:
- name: "debian"
  env:
    DEB: "on"
  deb:
    dh_make:
    - "--copyright=gpl3"
    - "--single"
    - "--templates=../build-scope/tpls/debian"
    - "--yes"
    - "--createorig"
    dpkg_buildpackage:
    - "-us"
    - "-uc"
- name: "centos"
  env:
    RPM: "on"
  rpm:
    cmake:
    - "."
    make:
    - "package"
